export const INITIALIZED = "example.app.INITIALIZED";
export const ROOT_CHANGED = "example.app.ROOT_CHANGED";
export const USER_REGISTERATION = "USER_REGISTERATION";
export const SET_NAVIGATOR = "SET_NAVIGATOR";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT = "LOGOUT";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOADING = "LOADING";

export const GET_INSTITUTIONS = "GET_INSTITUTIONS";
export const INSTITUTIONS = "INSTITUTIONS";
export const INSTITUTIONS_FAIL = "INSTITUTIONS_FAIL";

export const USER_DATA_SIGNUP = "USER_DATA_SIGNUP";

export const GET_CODE_INFO_REQUEST = "GET_CODE_INFO_REQUEST";
export const GET_CODE_INFO = "GET_CODE_INFO";
export const GET_CODE_INFO_REQUEST_FAIL = "GET_CODE_INFO_REQUEST_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN = "LOGIN";
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL";

export const LOGINBYSDEI_REQUEST = "LOGINBYSDEI_REQUEST";
export const LOGINBYSDEI_SUCCESS = "LOGINBYSDEI_SUCCESS";
export const LOGINBYSDEI_FAIL = "LOGINBYSDEI_FAIL";

export const CHECK_MOBILE_REQUEST = "CHECK_MOBILE_REQUEST";
export const CHECK_MOBILE_SUCCESS = "CHECK_MOBILE_SUCCESS";
export const CHECK_MOBILE_FAIL = "CHECK_MOBILE_FAIL";

export const GET_AAROGYA_TOKEN_REQUEST = "GET_AAROGYA_TOKEN_REQUEST";
export const GET_AAROGYA_TOKEN_SUCCESS = "GET_AAROGYA_TOKEN_SUCCESS";
export const GET_AAROGYA_TOKEN_FAIL = "GET_AAROGYA_TOKEN_FAIL";

export const SAVE_AAROGYA_REQUESTID_REQUEST = "SAVE_AAROGYA_REQUESTID_REQUEST";
export const SAVE_AAROGYA_REQUESTID_SUCCESS = "SAVE_AAROGYA_REQUESTID_SUCCESS";
export const SAVE_AAROGYA_REQUESTID_FAILED = "SAVE_AAROGYA_REQUESTID_FAILED";

export const AAROGYA_USERSTATUS_REQUEST = "AAROGYA_USERSTATUS_REQUEST";
export const AAROGYA_USERSTATUS_SUCCESS = "AAROGYA_USERSTATUS_SUCCESS";
export const AAROGYA_USERSTATUS_FAIL = "AAROGYA_USERSTATUS_FAIL";

export const AAROGYA_USERSTATUSBYID_REQUEST = "AAROGYA_USERSTATUSBYID_REQUEST";
export const AAROGYA_USERSTATUSBYID_SUCCESS = "AAROGYA_USERSTATUSBYID_SUCCESS";
export const AAROGYA_USERSTATUSBYID_FAIL = "AAROGYA_USERSTATUSBYID_FAIL";

export const IS_INTROSCREEN_WATHCED = "IS_INTROSCREEN_WATHCED";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_REQUEST_SUCCESS = "REGISTER_REQUEST_SUCCESS";
export const REGISTER_REQUEST_FAIL = "REGISTER_REQUEST_FAIL";

export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const EMPLOYEES_ACTIVITIES_REQUEST = "EMPLOYEES_ACTIVITIES_REQUEST";
export const EMPLOYEES_ACTIVITIES_SUCCESS = "EMPLOYEES_ACTIVITIES_SUCCESS";
export const EMPLOYEES_ACTIVITIES_FAILED = "EMPLOYEES_ACTIVITIES_FAILED";

export const EMPLOYEES_LASTACTIVE_REQUEST = "EMPLOYEES_LASTACTIVE_REQUEST";
export const EMPLOYEES_LASTACTIVE_SUCCESS = "EMPLOYEES_LASTACTIVE_SUCCESS";
export const EMPLOYEES_LASTACTIVE_FAILED = "EMPLOYEES_LASTACTIVE_FAILED";

export const GET_HOTSPOTS_REQUEST = "GET_HOTSPOTS_REQUEST";
export const GET_HOTSPOTS_SUCCESS = "GET_HOTSPOTS_SUCCESS";
export const GET_HOTSPOTS_FAILED = "GET_HOTSPOTS_FAILED";

export const GET_EMPLOYEEDATA_REQUEST = "GET_EMPLOYEEDATA_REQUEST";
export const GET_EMPLOYEEDATA_SUCCESS = "GET_EMPLOYEEDATA_SUCCESS";
export const GET_EMPLOYEEDATA_FAILED = "GET_EMPLOYEEDATA_FAILED";

export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILED = "EDIT_PROFILE_FAILED";

export const ADD_HOTSPOT_SUCCESS = "ADD_HOTSPOT_SUCCESS";
export const UPDATE_HOTSPOT_SUCCESS = "UPDATE_HOTSPOT_SUCCESS";
export const DELETE_HOTSPOT_SUCCESS = "DELETE_HOTSPOT_SUCCESS";

export const MY_ACTIVITIES_REQUEST = "MY_ACTIVITIES_REQUEST";
export const MY_ACTIVITIES_SUCCESS = "MY_ACTIVITIES_SUCCESS";
export const MY_ACTIVITIES_FAILED = "MY_ACTIVITIES_FAILED";

export const ALERT_ACTIVITIES_REQUEST = "ALERT_ACTIVITIES_REQUEST";
export const ALERT_ACTIVITIES_SUCCESS = "ALERT_ACTIVITIES_SUCCESS";
export const ALERT_ACTIVITIES_FAILED = "ALERT_ACTIVITIES_FAILED";

export const ADD_QUESTIONS_REQUEST = "ADD_QUESTIONS_REQUEST";
export const ADD_QUESTIONS_SUCCESS = "ADD_QUESTIONS_SUCCESS";
export const ADD_QUESTIONS_FAILED = "ADD_QUESTIONS_FAILED";

export const QUESTIONS_LIST_REQUEST = "QUESTIONS_LIST_REQUEST";
export const QUESTIONS_LIST_SUCCESS = "QUESTIONS_LIST_SUCCESS";
export const QUESTIONS_LIST_FAILED = "QUESTIONS_LIST_FAILED";

export const VERIFY_REQUEST_SUCCESS = "VERIFY_REQUEST_SUCCESS";
export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_REQUEST_FAIL = "VERIFY_REQUEST_FAIL";

export const POSIMATION_REQUEST = "POSIMATION_REQUEST";
export const POSIMATION_SUCESS = "POSIMATION_SUCESS";
export const POSIMATION_FAIL = "POSIMATION_FAIL";

export const POSIMATION_DELETE_REQUEST = "POSIMATION_DELETE_REQUEST";
export const POSIMATION_DELETE_SUCESS = "POSIMATION_DELETE_SUCESS";
export const POSIMATION_DELETE_FAIL = "POSIMATION_DELETE_FAIL";

export const BOT_IMAGE_SET = "BOT_IMAGE_SET";
export const BOT_CHAT_IMAGE_SET = "BOT_CHAT_IMAGE_SET";
export const BOT_NAME_CHANGE = "BOT_NAME_CHANGE";
export const BOT_SWITCH = "BOT_SWITCH";
export const SLOT_SAVE = "SLOT_SAVE";
export const TEXT_INPUT_CHAT = "TEXT_INPUT_CHAT";
export const TEXT_INPUT_TEN_NUMBER = "TEXT_INPUT_TEN_NUMBER";
export const TEXT_INPUT_ADD_MESSAGE = "TEXT_INPUT_ADD_MESSAGE";
export const RECURSION_VALUE_SET = "RECURSION_VALUE_SET";
export const TEXT_INPUT_NUMBER = "TEXT_INPUT_NUMBER";
export const POPOVERVIEW = "POPOVERVIEW";
export const VIDEO_BUTTON = "VIDEO_BUTTON";
export const VIDEO_SAVE = "VIDEO_SAVE";
export const VIDEO_PERCENTAGE_SET = "VIDEO_PERCENTAGE_SET";
export const AVATAR_IMAGES = "AVATAR_IMAGES";
export const AVATAR_IMAGES_FAIL = "AVATAR_IMAGES_FAIL";
export const SET_FCM_DEVICE_TOKEN = "SET_FCM_DEVICE_TOKEN";
export const SAVE_QUESTIONNAIRE_ID = "SAVE_QUESTIONNAIRE_ID";
export const RESEND_CODE = "RESEND_CODE";
export const SEND_BACK_TO_SERVER = "SEND_BACK_TO_SERVER";
export const SET_GUIDE_DESCRIPTION = "SET_GUIDE_DESCRIPTION";

export const OOZ_CHALLENGE_SHOW = "OOZ_CHALLENGE_SHOW";
export const SELECTED_TAB = "SELECTED_TAB";
export const SELECTED_SCREEN = "SELECTED_SCREEN";
export const LOGIN_USER = "LOGIN_USER";
export const SKIP_PROMPT_BUTTON = "SKIP_PROMPT_BUTTON";
export const CHALLENGE_TAB_PUSHED = "CHALLENGE_TAB_PUSHED";
export const END_OF_VALIDATION_TIMESTAMP = "END_OF_VALIDATION_TIMESTAMP";
export const TEXT_INPUT_CHAT_CLOSE_ALL = "TEXT_INPUT_CHAT_CLOSE_ALL";
export const AJIVAR_GUIDE_SHOW_OR_NOT = "AJIVAR_GUIDE_SHOW_OR_NOT";
export const CLEAR_STEPS = "CLEAR_STEPS";
export const CLEAR_POSIMATION_DATA = "CLEAR_POSIMATION_DATA";

export const GET_ASSESSMENT_QUESTIONS = "GET_ASSESSMENT_QUESTIONS";
export const GET_ASSESMENT_SUMMARY = "GET_ASSESMENT_SUMMARY";
export const INFERMEDICA_LOADER_ON = "INFERMEDICA_LOADER_ON";
export const INFERMEDICA_LOADER_OFF = "INFERMEDICA_LOADER_OFF";
export const CLEAR_INFERMEDICA_VALUES = "CLEAR_INFERMEDICA_VALUES";
